name: Generate Snake Animation

on:
  push:
    branches:
    - master  # ou 'main' dependendo do seu repositório

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate Snake Animation
        uses: Platane/snk@v2.0.0
        with:
          github_user_name: xigorbernardox
          outputs: dist/snake.svg
      - name: Push Snake Animation to the output branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          force_orphan: true
          keep_files: true
          commit_message: "Generate Snake Animation"
